### ISSUE TITLE
Pirate's Chart Mobs Need Scent Tracking / Deaggro & Despawn Easily

### ISSUE THREAD

**Issue by perkuprightmeow** [EdenServer/community#4456]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

30181205_0

Pirate's Chart mobs should have Scent tracking. https://youtu.be/hqfdR1DEfh0?t=53 this video shows Fenrir dying at 1:28 into the video. almost a minute later and the mobs are still chasing the SMN. Without scent tracking the mobs will deaggro when kited and depop earlier than they should, resulting in a lost fight.

**Comment by slassen** [comment]
Iirc water loses scent. So maybe they don’t have scent tracking but shouldn’t deaggro in another way

**Comment by 59blargedy** [comment]
resolved in October 4, 2021 update
