### ISSUE TITLE
Nyzul Mob True Sight/Sound Error Checklist

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#4783]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

v30181205

Carmine Erucas

Anyone who encounters any more, just add onto this report.

**Comment by falzum** [comment]
Coming to 2nd that carmine eruca in nyzul are set to true sound when they should be normal sound

**Comment by KnowOne134** [comment]
corrected 1/19/2022
